### ISSUE TITLE
Add offline support (PWA - service worker)

### ISSUE THREAD

**Issue by ajitid** [ajitid/meme-creator#1]

**Comment by marcelorl** [comment]
working on it

**Comment by ajitid** [comment]
@marcelorl, this issue has approved pull request by @aakash18012 now. Please don't work on it.

**Comment by ajitid** [comment]
@marcelorl, this issue has approved pull request of @aakash18012. Please don't work on it. Thanks

**Comment by marcelorl** [comment]
ok
